version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test2
      # You should definitely change the password in production
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db:
    driver: local
###< doctrine/doctrine-bundle ###
