version: '3'

services:
  database:
    env_file:
      - ./.env
    image: postgres:13-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
