/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable react/react-in-jsx-scope */
/* eslint-disable import/extensions */
import ApolloWrapper from '@/src/lib/apollo-wrapper'

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Id Page',
  description: 'Generated by create next app',
  keywords: 'Next.js, TypeScript, GraphQL, Apollo, Tailwind CSS',
}

const SuspenseLayout = ({ children }: any) => (
  <ApolloWrapper>
    {children}
  </ApolloWrapper>
)

export default SuspenseLayout
