/* eslint-disable react/react-in-jsx-scope */
import { Inter } from 'next/font/google'
import ApolloWrapper from '../lib/apollo-wrapper'
import AppWrapper from '../lib/app-wrapper'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'Next.js, TypeScript, GraphQL, Apollo, Tailwind CSS',
}

export const dynamic = 'force-dynamic'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => (
  <html lang="en" className={inter.className}>
    <body>
      <ApolloWrapper>
        <AppWrapper>
          {children}
        </AppWrapper>
      </ApolloWrapper>
    </body>
  </html>
)

export default RootLayout
