#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BLUE='\033[0;34m'
RED='\033[1;31m'
NC='\033[0m' # No Color

current_branch=`git rev-parse --abbrev-ref HEAD`
if [[ $current_branch =~ master|main ]]; then
    message="Please don't commit directly to $current_branch."
    echo -e "${RED}ERROR: $message${NC}";
    exit 1
fi