name: API (Laravel 9 - GraphQL - PostgreSQL) - CI/CD
on:
  push:
    branches: ['dev', 'master']

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}

jobs:
  # ---------------------------------------------------------------------------- #
  #                                   Tests job                                  #
  # ---------------------------------------------------------------------------- #
  Tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.3'

    steps:
      - uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl"
          ini-values: "memory_limit=-1, error_reporting=E_ALL, display_errors=On"
          php-version: "${{ matrix.php-version }}"

      - name: Install dependencies
        run: |
          cd api/
          composer install

      - name: Run PHPUnit
        run: |
          cd api/
          ./vendor/bin/phpunit

  # ---------------------------------------------------------------------------- #
  #                                Deployment job                                #
  # ---------------------------------------------------------------------------- #
  Deploy:
    needs: 'Tests'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.3'

    steps:
      - uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          extensions: "intl"
          ini-values: "memory_limit=-1, error_reporting=E_ALL, display_errors=On"
          php-version: "${{ matrix.php-version }}"

      - name: Install the Railway CLI
        run: npm i -g @railway/cli

      - name: Install dependencies
        run: |
          cd api/
          composer install
      
      # - name: Run migrations
      #   run: |
      #     cd api/
      #     railway run php artisan migrate:fresh --seed -n --force

      - name: Deployment to Railway
        run: railway up --service ecommerce-dxp
